
-- Decompiled with the Synapse X Luau decompiler.

return {
	IceQueenKit = {
		DAMAGE_REQUIREMENT = 250, 
		PASSIVE_STACK_COOLDOWN = 0.25, 
		PROC_COOLDOWN = 3, 
		BAR_COUNT = 4, 
		BASE_PASSIVE_DAMAGE = 0, 
		BASE_SPEED_MULTIPLIER = 0.6, 
		BASE_SLOW_LENGTH = 1.6, 
		ICE_SWORD_PASSIVE_DAMAGE = 0, 
		ICE_SWORD_SPEED_MULTIPLIER = 0.3, 
		ICE_SWORD_SLOW_LENGTH = 2.5, 
		ICE_SWORD_STUN_DURATION = 0.3, 
		PASSIVE_EXPIRATION_TIME = 10
	}
};

