-- Decompiled with the Synapse X Luau decompiler.

local v1 = {};
local v2 = setmetatable({}, {
	__index = v1
});
v2.DODO_BIRD = "DODO_BIRD";
v1.DODO_BIRD = "DODO_BIRD";
v2.AXOLOTL = "AXOLOTL";
v1.AXOLOTL = "AXOLOTL";
v2.POTION = "POTION";
v1.POTION = "POTION";
v2.LAUNCH_PAD = "launch_pad";
v1.launch_pad = "LAUNCH_PAD";
v2.SHIELD_GEN_ENCHANT = "SHIELD_GEN_ENCHANT";
v1.SHIELD_GEN_ENCHANT = "SHIELD_GEN_ENCHANT";
v2.TURTLE_SHELL = "TURTLE_SHELL";
v1.TURTLE_SHELL = "TURTLE_SHELL";
v2.LIFE_STEAL_SHIELD = "LIFE_STEAL_SHIELD";
v1.LIFE_STEAL_SHIELD = "LIFE_STEAL_SHIELD";
v2.SPIRIT_ASSASSIN = "SPIRIT_ASSASSIN";
v1.SPIRIT_ASSASSIN = "SPIRIT_ASSASSIN";
v2.BATTERY_KIT = "BATTERY_KIT";
v1.BATTERY_KIT = "BATTERY_KIT";
return {
	ShieldType = v2
};
