-- Script Hash: d6d9de50890471f96d614891f9d054869e97dbf077b59667a80967905ed6ac3da6a516f1f37c99697319b8bbca171fb5
-- Decompiled with the Synapse X Luau decompiler.

local l__BattlePassSeason__1 = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib")).import(script, game:GetService("ReplicatedStorage"), "TS", "battle-pass", "battle-pass-seasons").BattlePassSeason;
local v2 = {};
local v3 = setmetatable({}, {
	__index = v2
});
v3.NONE = "none";
v2.none = "NONE";
v3.FARMER_CLETUS = "farmer_cletus";
v2.farmer_cletus = "FARMER_CLETUS";
v3.BARBARIAN = "barbarian";
v2.barbarian = "BARBARIAN";
v3.BUILDER = "builder";
v2.builder = "BUILDER";
v3.BAKER = "baker";
v2.baker = "BAKER";
v3.ARCHER = "archer";
v2.archer = "ARCHER";
v3.SHIELDER = "shielder";
v2.shielder = "SHIELDER";
v3.MELODY = "melody";
v2.melody = "MELODY";
v3.DAVEY = "davey";
v2.davey = "DAVEY";
v3.BIGMAN = "bigman";
v2.bigman = "BIGMAN";
v3.COWGIRL = "cowgirl";
v2.cowgirl = "COWGIRL";
v3.GRIM_REAPER = "grim_reaper";
v2.grim_reaper = "GRIM_REAPER";
v3.WIZARD = "wizard";
v2.wizard = "WIZARD";
v3.VULCAN = "vulcan";
v2.vulcan = "VULCAN";
v3.PYRO = "pyro";
v2.pyro = "PYRO";
v3.RAVEN = "raven";
v2.raven = "RAVEN";
v3.BEEKEEPER = "beekeeper";
v2.beekeeper = "BEEKEEPER";
v3.JADE = "jade";
v2.jade = "JADE";
v3.WARRIOR = "warrior";
v2.warrior = "WARRIOR";
v3.BOUNTY_HUNTER = "bounty_hunter";
v2.bounty_hunter = "BOUNTY_HUNTER";
v3.SPIRIT_CATCHER = "spirit_catcher";
v2.spirit_catcher = "SPIRIT_CATCHER";
v3.ANGEL = "angel";
v2.angel = "ANGEL";
v3.AXOLOTL = "axolotl";
v2.axolotl = "AXOLOTL";
v3.TRAPPER = "trapper";
v2.trapper = "TRAPPER";
v3.FISHERMAN = "fisherman";
v2.fisherman = "FISHERMAN";
v3.GHOST_CATCHER = "ghost_catcher";
v2.ghost_catcher = "GHOST_CATCHER";
v3.OIL_MAN = "oil_man";
v2.oil_man = "OIL_MAN";
v3.SPEARMAN = "spearman";
v2.spearman = "SPEARMAN";
v3.TRIPLE_SHOT = "triple_shot";
v2.triple_shot = "TRIPLE_SHOT";
v3.INFECTED = "infected";
v2.infected = "INFECTED";
v3.SUPER_INFECTED = "super_infected";
v2.super_infected = "SUPER_INFECTED";
v3.ICE_QUEEN = "ice_queen";
v2.ice_queen = "ICE_QUEEN";
v3.AERY = "aery";
v2.aery = "AERY";
v3.YETI = "yeti";
v2.yeti = "YETI";
v3.GINGERBREAD_MAN = "gingerbread_man";
v2.gingerbread_man = "GINGERBREAD_MAN";
v3.SANTA = "santa";
v2.santa = "SANTA";
v3.REGENT = "regent";
v2.regent = "REGENT";
v3.FROSTY = "frosty";
v2.frosty = "FROSTY";
v3.SMOKE = "smoke";
v2.smoke = "SMOKE";
v3.DASHER = "dasher";
v2.dasher = "DASHER";
v3.ALCHEMIST = "alchemist";
v2.alchemist = "ALCHEMIST";
v3.MINER = "miner";
v2.miner = "MINER";
v3.MIDNIGHT = "midnight";
v2.midnight = "MIDNIGHT";
v3.SHEEP_HERDER = "sheep_herder";
v2.sheep_herder = "SHEEP_HERDER";
v3.BEAST = "beast";
v2.beast = "BEAST";
v3.METAL_DETECTOR = "metal_detector";
v2.metal_detector = "METAL_DETECTOR";
v3.CYBER = "cyber";
v2.cyber = "CYBER";
v3.CONQUEROR = "vesta";
v2.vesta = "CONQUEROR";
v3.LUMEN = "lumen";
v2.lumen = "LUMEN";
v3.EMBER = "ember";
v2.ember = "EMBER";
v3.MERCHANT = "merchant";
v2.merchant = "MERCHANT";
v3.DINO_TAMER = "dino_tamer";
v2.dino_tamer = "DINO_TAMER";
v3.WIND_WALKER = "wind_walker";
v2.wind_walker = "WIND_WALKER";
v3.STAR_COLLECTOR = "star_collector";
v2.star_collector = "STAR_COLLECTOR";
return {
	BedwarsKit = v3, 
	BedwarsBPKits = {
		[l__BattlePassSeason__1.season1] = { v3.PYRO, v3.RAVEN, v3.BEEKEEPER, v3.SPIRIT_CATCHER, v3.BOUNTY_HUNTER, v3.JADE, v3.WARRIOR }, 
		[l__BattlePassSeason__1.season2] = { v3.SPEARMAN, v3.FISHERMAN, v3.TRAPPER, v3.OIL_MAN, v3.GHOST_CATCHER }, 
		[l__BattlePassSeason__1.season3] = { v3.FROSTY, v3.SANTA, v3.SMOKE, v3.YETI, v3.AERY, v3.GINGERBREAD_MAN }, 
		[l__BattlePassSeason__1.season4] = { v3.MIDNIGHT, v3.ALCHEMIST, v3.BEAST, v3.SHEEP_HERDER, v3.METAL_DETECTOR, v3.CONQUEROR }, 
		[l__BattlePassSeason__1.season5] = { v3.WIND_WALKER, v3.STAR_COLLECTOR, v3.DINO_TAMER, v3.MERCHANT }
	}
};
