-- Decompiled with the Synapse X Luau decompiler.

return {
	BalanceFile = {
		SNOW_CONE_ARROW_COST = 1, 
		SNOW_CONE_BLOCK_COST = 3, 
		SNOW_CONE_SWORD_COST = 5, 
		SNOW_CONE_ARROW_BASE_DMG = 1.3, 
		SNOW_CONE_ARROW_STACK_BONUS = 0.01, 
		SNOW_CONE_BLOCK_BASE_DMG = 1.5, 
		SNOW_CONE_BLOCK_STACK_BONUS = 0.01, 
		SNOW_CONE_SWORD_BASE_DMG = 1.3, 
		SNOW_CONE_SWORD_STACK_BONUS = 0.04, 
		RepairSnowConeMachinePrice = 5, 
		RepairSnowConeMachineCurrency = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib")).import(script, game:GetService("ReplicatedStorage"), "TS", "item", "item-type").ItemType.DIAMOND, 
		VOLLEY_ENCHANT_COOLDOWN = 2.75, 
		VOLLEY_ENCHANT_ARROW_COUNT = 4, 
		WALL_HEIGHT = 5, 
		WALL_HALF_WIDTH = 4, 
		TNT_WARS_DRONE_COOLDOWN = 60, 
		TNT_WARS_BALLOON_COUNT = 8, 
		TNT_WARS_BALLOON_TNT_COUNT = 8, 
		TNT_WARS_BALLOON_TRAVEL_TIME = 30, 
		TNT_WARS_BALLOON_NUMBER_ROTATIONS = 3, 
		EVELYNN_INTERNAL_COOLDOWN = 5, 
		HANNAH_BASE_EXECUTE_THRESHOLD = 0.25, 
		HANNAH_MAX_COMBO = 3, 
		HANNAH_COMBO_EXECUTE_BOOST = 0.06, 
		HANNAH_COMBO_EXPIRATION_SEC = 8, 
		PIRATE_TELESCOPE_DURATION = 5, 
		PIRATE_TELESCOPE_RANGE = 15, 
		PIRATE_SHOVEL_IRON = 60, 
		PIRATE_SHOVEL_DIAMOND = 112, 
		PIRATE_SHOVEL_EMERALD = 130, 
		PIRATE_FLAG_RANGE = 30
	}
};
