-- Decompiled with the Synapse X Luau decompiler.

return {
	VoidDragonBalance = {
		BREATH_DURATION = 0.5, 
		BREATH_DAMAGE_PER_TICK = 10, 
		BREATH_TICK_PER_SECOND = 5, 
		BREATH_COOLDOWN = 1, 
		BREATH_CONSUMPTION = -5, 
		BREATH_RANGE = 25, 
		ENERGY_DECAY_PER_SECOND = -2, 
		FLAP_WINGS_COST = -20, 
		TRANSFORM_RADIUS = 15, 
		ENERGY_GAIN_PER_SECOND = 0.5, 
		ENERGY_GAIN_PER_KILL = 25, 
		TELEPEARL_ENERGY_GAIN = 7
	}
};
