-- Decompiled with the Synapse X Luau decompiler.

local v1 = {};
local v2 = {};
v2.__index = v2;
local u1 = require(game:GetService("Chat"):WaitForChild("ClientChatModules"):WaitForChild("ChatSettings"));
function v2.Destroy(p1)
	p1.GuiObject:Destroy();
end;
function v2.UpdateMessagePostedInChannel(p2, p3)
	if p2.Active and p3 ~= true then
		return;
	end;
	local v3 = p2.UnreadMessageCount + 1;
	p2.UnreadMessageCount = v3;
	local l__NewMessageIcon__4 = p2.NewMessageIcon;
	l__NewMessageIcon__4.Visible = true;
	l__NewMessageIcon__4.TextLabel.Text = v3 < 100 and tostring(v3) or "!";
	local v5 = l__NewMessageIcon__4.Position + UDim2.new(0, 0, -0.1, 0);
	l__NewMessageIcon__4.Position = UDim2.new(0, 0, -0.15, 0);
	l__NewMessageIcon__4:TweenPosition(UDim2.new(0, 0, 0, 0), Enum.EasingDirection.Out, Enum.EasingStyle.Quad, 0.15, true);
end;
function v2.SetActive(p4, p5)
	p4.Active = p5;
	p4.UnselectedFrame.Visible = not p5;
	p4.SelectedFrame.Visible = p5;
	if not p5 then
		p4.NameTag.Font = Enum.Font.SourceSans;
		return;
	end;
	p4.UnreadMessageCount = 0;
	p4.NewMessageIcon.Visible = false;
	p4.NameTag.Font = Enum.Font.SourceSansBold;
end;
function v2.SetTextSize(p6, p7)
	p6.NameTag.TextSize = p7;
end;
local u2 = require(script.Parent:WaitForChild("CurveUtil"));
function v2.FadeOutBackground(p8, p9)
	p8.AnimParams.Background_TargetTransparency = 1;
	p8.AnimParams.Background_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(p9);
end;
function v2.FadeInBackground(p10, p11)
	p10.AnimParams.Background_TargetTransparency = 0.6;
	p10.AnimParams.Background_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(p11);
end;
function v2.FadeOutText(p12, p13)
	p12.AnimParams.Text_TargetTransparency = 1;
	p12.AnimParams.Text_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(p13);
	p12.AnimParams.TextStroke_TargetTransparency = 1;
	p12.AnimParams.TextStroke_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(p13);
end;
function v2.FadeInText(p14, p15)
	p14.AnimParams.Text_TargetTransparency = 0;
	p14.AnimParams.Text_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(p15);
	p14.AnimParams.TextStroke_TargetTransparency = 0.75;
	p14.AnimParams.TextStroke_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(p15);
end;
function v2.AnimGuiObjects(p16)
	p16.UnselectedFrame.BackgroundTransparency = p16.AnimParams.Background_CurrentTransparency;
	p16.SelectedFrame.BackgroundImage.BackgroundTransparency = p16.AnimParams.Background_CurrentTransparency;
	p16.SelectedFrame.BlueBarLeft.ImageTransparency = p16.AnimParams.Background_CurrentTransparency;
	p16.SelectedFrame.BlueBarRight.ImageTransparency = p16.AnimParams.Background_CurrentTransparency;
	p16.NameTagNonSelect.TextTransparency = p16.AnimParams.Background_CurrentTransparency;
	p16.NameTagNonSelect.TextStrokeTransparency = p16.AnimParams.Background_CurrentTransparency;
	p16.NameTag.TextTransparency = p16.AnimParams.Text_CurrentTransparency;
	p16.NewMessageIcon.ImageTransparency = p16.AnimParams.Text_CurrentTransparency;
	p16.WhiteTextNewMessageNotification.TextTransparency = p16.AnimParams.Text_CurrentTransparency;
	p16.NameTagSelect.TextTransparency = p16.AnimParams.Text_CurrentTransparency;
	p16.NameTag.TextStrokeTransparency = p16.AnimParams.TextStroke_CurrentTransparency;
	p16.WhiteTextNewMessageNotification.TextStrokeTransparency = p16.AnimParams.TextStroke_CurrentTransparency;
	p16.NameTagSelect.TextStrokeTransparency = p16.AnimParams.TextStroke_CurrentTransparency;
end;
function v2.InitializeAnimParams(p17)
	p17.AnimParams.Text_TargetTransparency = 0;
	p17.AnimParams.Text_CurrentTransparency = 0;
	p17.AnimParams.Text_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(0);
	p17.AnimParams.TextStroke_TargetTransparency = 0.75;
	p17.AnimParams.TextStroke_CurrentTransparency = 0.75;
	p17.AnimParams.TextStroke_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(0);
	p17.AnimParams.Background_TargetTransparency = 0.6;
	p17.AnimParams.Background_CurrentTransparency = 0.6;
	p17.AnimParams.Background_NormalizedExptValue = u2:NormalizedDefaultExptValueInSeconds(0);
end;
function v2.Update(p18, p19)
	p18.AnimParams.Background_CurrentTransparency = u2:Expt(p18.AnimParams.Background_CurrentTransparency, p18.AnimParams.Background_TargetTransparency, p18.AnimParams.Background_NormalizedExptValue, p19);
	p18.AnimParams.Text_CurrentTransparency = u2:Expt(p18.AnimParams.Text_CurrentTransparency, p18.AnimParams.Text_TargetTransparency, p18.AnimParams.Text_NormalizedExptValue, p19);
	p18.AnimParams.TextStroke_CurrentTransparency = u2:Expt(p18.AnimParams.TextStroke_CurrentTransparency, p18.AnimParams.TextStroke_TargetTransparency, p18.AnimParams.TextStroke_NormalizedExptValue, p19);
	p18:AnimGuiObjects();
end;
local function u3()
	local v6 = Instance.new("Frame");
	v6.Selectable = false;
	v6.Size = UDim2.new(1, 0, 1, 0);
	v6.BackgroundTransparency = 1;
	local v7 = Instance.new("Frame");
	v7.Selectable = false;
	v7.Name = "BackgroundFrame";
	v7.Size = UDim2.new(1, -2, 1, -2);
	v7.Position = UDim2.new(0, 1, 0, 1);
	v7.BackgroundTransparency = 1;
	v7.Parent = v6;
	local v8 = Instance.new("Frame");
	v8.Selectable = false;
	v8.Name = "UnselectedFrame";
	v8.Size = UDim2.new(1, 0, 1, 0);
	v8.Position = UDim2.new(0, 0, 0, 0);
	v8.BorderSizePixel = 0;
	v8.BackgroundColor3 = u1.ChannelsTabUnselectedColor;
	v8.BackgroundTransparency = 0.6;
	v8.Parent = v7;
	local v9 = Instance.new("Frame");
	v9.Selectable = false;
	v9.Name = "SelectedFrame";
	v9.Size = UDim2.new(1, 0, 1, 0);
	v9.Position = UDim2.new(0, 0, 0, 0);
	v9.BorderSizePixel = 0;
	v9.BackgroundColor3 = u1.ChannelsTabSelectedColor;
	v9.BackgroundTransparency = 1;
	v9.Parent = v7;
	local v10 = Instance.new("ImageLabel");
	v10.Selectable = false;
	v10.Name = "BackgroundImage";
	v10.BackgroundTransparency = 1;
	v10.BorderSizePixel = 0;
	v10.Size = UDim2.new(1, 0, 1, 0);
	v10.Position = UDim2.new(0, 0, 0, 0);
	v10.ScaleType = Enum.ScaleType.Slice;
	v10.Parent = v9;
	v10.BackgroundTransparency = -0.4;
	v10.BackgroundColor3 = Color3.fromRGB(93.6, 100.8, 115.19999999999999);
	local v11 = Instance.new("ImageLabel");
	v11.Selectable = false;
	v11.Size = UDim2.new(0.5, -2, 0, 4);
	v11.BackgroundTransparency = 1;
	v11.ScaleType = Enum.ScaleType.Slice;
	v11.SliceCenter = Rect.new(3, 3, 32, 21);
	v11.Parent = v9;
	local v12 = v11:Clone();
	v12.Parent = v9;
	v11.Position = UDim2.new(0, 2, 1, -4);
	v12.Position = UDim2.new(0.5, 0, 1, -4);
	v11.Image = "rbxasset://textures/ui/Settings/Slider/SelectedBarLeft.png";
	v12.Image = "rbxasset://textures/ui/Settings/Slider/SelectedBarRight.png";
	v11.Name = "BlueBarLeft";
	v12.Name = "BlueBarRight";
	local v13 = Instance.new("TextButton");
	v13.Selectable = u1.GamepadNavigationEnabled;
	v13.Size = UDim2.new(1, 0, 1, 0);
	v13.Position = UDim2.new(0, 0, 0, 0);
	v13.BackgroundTransparency = 1;
	v13.Font = u1.DefaultFont;
	v13.TextSize = u1.ChatChannelsTabTextSize;
	v13.TextColor3 = Color3.new(1, 1, 1);
	v13.TextStrokeTransparency = 0.75;
	v13.Parent = v7;
	local v14 = v13:Clone();
	local v15 = v13:Clone();
	v14.Parent = v8;
	v15.Parent = v9;
	v14.Font = Enum.Font.SourceSans;
	v14.Active = false;
	v15.Active = false;
	local v16 = Instance.new("Frame");
	v16.Selectable = false;
	v16.Size = UDim2.new(0, 18, 0, 18);
	v16.Position = UDim2.new(0.8, -9, 0.5, -9);
	v16.BackgroundTransparency = 1;
	v16.Parent = v7;
	local v17 = Instance.new("ImageLabel");
	v17.Selectable = false;
	v17.Size = UDim2.new(1, 0, 1, 0);
	v17.BackgroundTransparency = 1;
	v17.Image = "rbxasset://textures/ui/Chat/MessageCounter.png";
	v17.Visible = false;
	v17.Parent = v16;
	local v18 = Instance.new("TextLabel");
	v18.Selectable = false;
	v18.BackgroundTransparency = 1;
	v18.Size = UDim2.new(0, 13, 0, 9);
	v18.Position = UDim2.new(0.5, -7, 0.5, -7);
	v18.Font = u1.DefaultFont;
	v18.TextSize = 14;
	v18.TextColor3 = Color3.new(1, 1, 1);
	v18.Text = "";
	v18.Parent = v17;
	return v6, v13, v14, v15, v17, v8, v9;
end;
function v1.new(p20)
	local v19 = setmetatable({}, v2);
	local v20, v21, v22, v23, v24, v25, v26 = u3();
	v19.GuiObject = v20;
	v19.NameTag = v21;
	v19.NameTagNonSelect = v22;
	v19.NameTagSelect = v23;
	v19.NewMessageIcon = v24;
	v19.UnselectedFrame = v25;
	v19.SelectedFrame = v26;
	v19.BlueBarLeft = v26.BlueBarLeft;
	v19.BlueBarRight = v26.BlueBarRight;
	v19.BackgroundImage = v26.BackgroundImage;
	v19.WhiteTextNewMessageNotification = v19.NewMessageIcon.TextLabel;
	v19.ChannelName = p20;
	v19.UnreadMessageCount = 0;
	v19.Active = false;
	v19.GuiObject.Name = "Frame_" .. v19.ChannelName;
	if u1.MaxChannelNameLength < string.len(p20) then
		p20 = string.sub(p20, 1, u1.MaxChannelNameLength - 3) .. "...";
	end;
	v19.NameTag.Text = "";
	v19.NameTagNonSelect.Text = p20;
	v19.NameTagSelect.Text = p20;
	v19.AnimParams = {};
	v19:InitializeAnimParams();
	v19:AnimGuiObjects();
	v19:SetActive(false);
	return v19;
end;
return v1;
