-- Decompiled with the Synapse X Luau decompiler.

local v1 = {};
local v2 = setmetatable({}, {
	__index = v1
});
v2.BLOOD_DEAL = "blood_deal";
v1.blood_deal = "BLOOD_DEAL";
v2.KNIGHTS_CODE = "knights_code";
v1.knights_code = "KNIGHTS_CODE";
v2.EMBERS_ANGUISH = "embers_anguish";
v1.embers_anguish = "EMBERS_ANGUISH";
v2.NATURES_TOUCH = "natures_touch";
v1.natures_touch = "NATURES_TOUCH";
v2.MELODYS_LULLABY = "melodys_lullaby";
v1.melodys_lullaby = "MELODYS_LULLABY";
v2.STOMPER = "stomper";
v1.stomper = "STOMPER";
v2.QUICK_FORGE = "quick_forge";
v1.quick_forge = "QUICK_FORGE";
v2.GLASS_CANNON = "glass_cannon";
v1.glass_cannon = "GLASS_CANNON";
v2.SWORD_MASTER = "sword_master";
v1.sword_master = "SWORD_MASTER";
v2.ELECTRIFIED = "electrified";
v1.electrified = "ELECTRIFIED";
v2.DOUBLE_HIT = "double_hit";
v1.double_hit = "DOUBLE_HIT";
v2.SECOND_WIND = "second_wind";
v1.second_wind = "SECOND_WIND";
v2.GLITCHED_ENCHANTING = "glitched_enchanting";
v1.glitched_enchanting = "GLITCHED_ENCHANTING";
v2.BLACKHOLE = "blackhole";
v1.blackhole = "BLACKHOLE";
v2.CASH_BACK = "cash_back";
v1.cash_back = "CASH_BACK";
v2.IRON_WILL = "iron_will";
v1.iron_will = "IRON_WILL";
v2.GREEDY = "greedy";
v1.greedy = "GREEDY";
v2.BASE_PROTECTOR = "base_protector";
v1.base_protector = "BASE_PROTECTOR";
v2.LOOTER = "looter";
v1.looter = "LOOTER";
v2.UNITY = "unity";
v1.unity = "UNITY";
v2.ESSENCE_OF_NATURE = "essence_of_nature";
v1.essence_of_nature = "ESSENCE_OF_NATURE";
v2.REINFORCED_BED = "reinforced_bed";
v1.reinforced_bed = "REINFORCED_BED";
v2.DRAGON_EGG = "dragon_egg";
v1.dragon_egg = "DRAGON_EGG";
v2.CALL_OF_THE_VOID = "call_of_the_void";
v1.call_of_the_void = "CALL_OF_THE_VOID";
v2.SNIPER = "sniper";
v1.sniper = "SNIPER";
v2.PROSPECTORS_DISCIPLINE = "prospectors_discipline";
v1.prospectors_discipline = "PROSPECTORS_DISCIPLINE";
v2.HEADSTART = "headstart";
v1.headstart = "HEADSTART";
v2.PIERCING_BLADE = "piercing_blade";
v1.piercing_blade = "PIERCING_BLADE";
return {
	RelicType = v2
};
