-- Decompiled with the Synapse X Luau decompiler.

local v1 = {};
local v2 = setmetatable({}, {
	__index = v1
});
v2.TNT = "TNT";
v1.TNT = "TNT";
v2.LUCKYBLOCK_TNT = "TNT";
v1.TNT = "LUCKYBLOCK_TNT";
v2.FIREBALL = "FIREBALL";
v1.FIREBALL = "FIREBALL";
v2.ROCKET_MISSILE = "ROCKET_MISSILE";
v1.ROCKET_MISSILE = "ROCKET_MISSILE";
v2.GUIDED_MISSILE = "GUIDED_MISSILE";
v1.GUIDED_MISSILE = "GUIDED_MISSILE";
v2.CARROT_ROCKET = "CARROT_ROCKET";
v1.CARROT_ROCKET = "CARROT_ROCKET";
v2.BOBA = "BOBA";
v1.BOBA = "BOBA";
v2.METEOR = "METEOR";
v1.METEOR = "METEOR";
v2.INVISIBLE_LANDMINE = "INVISIBLE_LANDMINE";
v1.INVISIBLE_LANDMINE = "INVISIBLE_LANDMINE";
v2.HELICOPTER = "helicopter";
v1.helicopter = "HELICOPTER";
return {
	ExplosionType = v2
};
